development:
  AWS_ACCESS_KEY_ID: 'AKIAJZB6EUE4ECJWIYXA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'designmatchg11'
test:
  AWS_ACCESS_KEY_ID: 'AKIAJZB6EUE4ECJWIYXA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'designmatchg11'
production:
  AWS_ACCESS_KEY_ID: 'AKIAJZB6EUE4ECJWIYXA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'designmatchg11'
