development:
  AWS_ACCESS_KEY_ID: 'AKIAJVPQ43NEK4KW5AIA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'designmatch-g11'
test:
  AWS_ACCESS_KEY_ID: 'AKIAJVPQ43NEK4KW5AIA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'designmatch-g11'
production:
  AWS_ACCESS_KEY_ID: 'AKIAJVPQ43NEK4KW5AIA'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'designmatch-g11'
